/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.zeppelin.interpreter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-06-18")
public class RestApiInfo implements org.apache.thrift.TBase<RestApiInfo, RestApiInfo._Fields>, java.io.Serializable, Cloneable, Comparable<RestApiInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RestApiInfo");

  private static final org.apache.thrift.protocol.TField INTP_GROUP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("intpGroupId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NOTE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("noteId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ENDPOINT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("endpointName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField HOSTNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("hostname", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SERVER_PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("serverPort", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RestApiInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RestApiInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String intpGroupId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String noteId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String endpointName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String hostname; // required
  public int serverPort; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INTP_GROUP_ID((short)1, "intpGroupId"),
    NOTE_ID((short)2, "noteId"),
    ENDPOINT_NAME((short)3, "endpointName"),
    HOSTNAME((short)4, "hostname"),
    SERVER_PORT((short)5, "serverPort");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTP_GROUP_ID
          return INTP_GROUP_ID;
        case 2: // NOTE_ID
          return NOTE_ID;
        case 3: // ENDPOINT_NAME
          return ENDPOINT_NAME;
        case 4: // HOSTNAME
          return HOSTNAME;
        case 5: // SERVER_PORT
          return SERVER_PORT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SERVERPORT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTP_GROUP_ID, new org.apache.thrift.meta_data.FieldMetaData("intpGroupId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NOTE_ID, new org.apache.thrift.meta_data.FieldMetaData("noteId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENDPOINT_NAME, new org.apache.thrift.meta_data.FieldMetaData("endpointName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOSTNAME, new org.apache.thrift.meta_data.FieldMetaData("hostname", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SERVER_PORT, new org.apache.thrift.meta_data.FieldMetaData("serverPort", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RestApiInfo.class, metaDataMap);
  }

  public RestApiInfo() {
  }

  public RestApiInfo(
    java.lang.String intpGroupId,
    java.lang.String noteId,
    java.lang.String endpointName,
    java.lang.String hostname,
    int serverPort)
  {
    this();
    this.intpGroupId = intpGroupId;
    this.noteId = noteId;
    this.endpointName = endpointName;
    this.hostname = hostname;
    this.serverPort = serverPort;
    setServerPortIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RestApiInfo(RestApiInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetIntpGroupId()) {
      this.intpGroupId = other.intpGroupId;
    }
    if (other.isSetNoteId()) {
      this.noteId = other.noteId;
    }
    if (other.isSetEndpointName()) {
      this.endpointName = other.endpointName;
    }
    if (other.isSetHostname()) {
      this.hostname = other.hostname;
    }
    this.serverPort = other.serverPort;
  }

  public RestApiInfo deepCopy() {
    return new RestApiInfo(this);
  }

  @Override
  public void clear() {
    this.intpGroupId = null;
    this.noteId = null;
    this.endpointName = null;
    this.hostname = null;
    setServerPortIsSet(false);
    this.serverPort = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getIntpGroupId() {
    return this.intpGroupId;
  }

  public RestApiInfo setIntpGroupId(@org.apache.thrift.annotation.Nullable java.lang.String intpGroupId) {
    this.intpGroupId = intpGroupId;
    return this;
  }

  public void unsetIntpGroupId() {
    this.intpGroupId = null;
  }

  /** Returns true if field intpGroupId is set (has been assigned a value) and false otherwise */
  public boolean isSetIntpGroupId() {
    return this.intpGroupId != null;
  }

  public void setIntpGroupIdIsSet(boolean value) {
    if (!value) {
      this.intpGroupId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNoteId() {
    return this.noteId;
  }

  public RestApiInfo setNoteId(@org.apache.thrift.annotation.Nullable java.lang.String noteId) {
    this.noteId = noteId;
    return this;
  }

  public void unsetNoteId() {
    this.noteId = null;
  }

  /** Returns true if field noteId is set (has been assigned a value) and false otherwise */
  public boolean isSetNoteId() {
    return this.noteId != null;
  }

  public void setNoteIdIsSet(boolean value) {
    if (!value) {
      this.noteId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEndpointName() {
    return this.endpointName;
  }

  public RestApiInfo setEndpointName(@org.apache.thrift.annotation.Nullable java.lang.String endpointName) {
    this.endpointName = endpointName;
    return this;
  }

  public void unsetEndpointName() {
    this.endpointName = null;
  }

  /** Returns true if field endpointName is set (has been assigned a value) and false otherwise */
  public boolean isSetEndpointName() {
    return this.endpointName != null;
  }

  public void setEndpointNameIsSet(boolean value) {
    if (!value) {
      this.endpointName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHostname() {
    return this.hostname;
  }

  public RestApiInfo setHostname(@org.apache.thrift.annotation.Nullable java.lang.String hostname) {
    this.hostname = hostname;
    return this;
  }

  public void unsetHostname() {
    this.hostname = null;
  }

  /** Returns true if field hostname is set (has been assigned a value) and false otherwise */
  public boolean isSetHostname() {
    return this.hostname != null;
  }

  public void setHostnameIsSet(boolean value) {
    if (!value) {
      this.hostname = null;
    }
  }

  public int getServerPort() {
    return this.serverPort;
  }

  public RestApiInfo setServerPort(int serverPort) {
    this.serverPort = serverPort;
    setServerPortIsSet(true);
    return this;
  }

  public void unsetServerPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVERPORT_ISSET_ID);
  }

  /** Returns true if field serverPort is set (has been assigned a value) and false otherwise */
  public boolean isSetServerPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVERPORT_ISSET_ID);
  }

  public void setServerPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVERPORT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case INTP_GROUP_ID:
      if (value == null) {
        unsetIntpGroupId();
      } else {
        setIntpGroupId((java.lang.String)value);
      }
      break;

    case NOTE_ID:
      if (value == null) {
        unsetNoteId();
      } else {
        setNoteId((java.lang.String)value);
      }
      break;

    case ENDPOINT_NAME:
      if (value == null) {
        unsetEndpointName();
      } else {
        setEndpointName((java.lang.String)value);
      }
      break;

    case HOSTNAME:
      if (value == null) {
        unsetHostname();
      } else {
        setHostname((java.lang.String)value);
      }
      break;

    case SERVER_PORT:
      if (value == null) {
        unsetServerPort();
      } else {
        setServerPort((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INTP_GROUP_ID:
      return getIntpGroupId();

    case NOTE_ID:
      return getNoteId();

    case ENDPOINT_NAME:
      return getEndpointName();

    case HOSTNAME:
      return getHostname();

    case SERVER_PORT:
      return getServerPort();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INTP_GROUP_ID:
      return isSetIntpGroupId();
    case NOTE_ID:
      return isSetNoteId();
    case ENDPOINT_NAME:
      return isSetEndpointName();
    case HOSTNAME:
      return isSetHostname();
    case SERVER_PORT:
      return isSetServerPort();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RestApiInfo)
      return this.equals((RestApiInfo)that);
    return false;
  }

  public boolean equals(RestApiInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_intpGroupId = true && this.isSetIntpGroupId();
    boolean that_present_intpGroupId = true && that.isSetIntpGroupId();
    if (this_present_intpGroupId || that_present_intpGroupId) {
      if (!(this_present_intpGroupId && that_present_intpGroupId))
        return false;
      if (!this.intpGroupId.equals(that.intpGroupId))
        return false;
    }

    boolean this_present_noteId = true && this.isSetNoteId();
    boolean that_present_noteId = true && that.isSetNoteId();
    if (this_present_noteId || that_present_noteId) {
      if (!(this_present_noteId && that_present_noteId))
        return false;
      if (!this.noteId.equals(that.noteId))
        return false;
    }

    boolean this_present_endpointName = true && this.isSetEndpointName();
    boolean that_present_endpointName = true && that.isSetEndpointName();
    if (this_present_endpointName || that_present_endpointName) {
      if (!(this_present_endpointName && that_present_endpointName))
        return false;
      if (!this.endpointName.equals(that.endpointName))
        return false;
    }

    boolean this_present_hostname = true && this.isSetHostname();
    boolean that_present_hostname = true && that.isSetHostname();
    if (this_present_hostname || that_present_hostname) {
      if (!(this_present_hostname && that_present_hostname))
        return false;
      if (!this.hostname.equals(that.hostname))
        return false;
    }

    boolean this_present_serverPort = true;
    boolean that_present_serverPort = true;
    if (this_present_serverPort || that_present_serverPort) {
      if (!(this_present_serverPort && that_present_serverPort))
        return false;
      if (this.serverPort != that.serverPort)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetIntpGroupId()) ? 131071 : 524287);
    if (isSetIntpGroupId())
      hashCode = hashCode * 8191 + intpGroupId.hashCode();

    hashCode = hashCode * 8191 + ((isSetNoteId()) ? 131071 : 524287);
    if (isSetNoteId())
      hashCode = hashCode * 8191 + noteId.hashCode();

    hashCode = hashCode * 8191 + ((isSetEndpointName()) ? 131071 : 524287);
    if (isSetEndpointName())
      hashCode = hashCode * 8191 + endpointName.hashCode();

    hashCode = hashCode * 8191 + ((isSetHostname()) ? 131071 : 524287);
    if (isSetHostname())
      hashCode = hashCode * 8191 + hostname.hashCode();

    hashCode = hashCode * 8191 + serverPort;

    return hashCode;
  }

  @Override
  public int compareTo(RestApiInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetIntpGroupId()).compareTo(other.isSetIntpGroupId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntpGroupId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intpGroupId, other.intpGroupId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNoteId()).compareTo(other.isSetNoteId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNoteId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.noteId, other.noteId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEndpointName()).compareTo(other.isSetEndpointName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndpointName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endpointName, other.endpointName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHostname()).compareTo(other.isSetHostname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostname, other.hostname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetServerPort()).compareTo(other.isSetServerPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServerPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serverPort, other.serverPort);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RestApiInfo(");
    boolean first = true;

    sb.append("intpGroupId:");
    if (this.intpGroupId == null) {
      sb.append("null");
    } else {
      sb.append(this.intpGroupId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("noteId:");
    if (this.noteId == null) {
      sb.append("null");
    } else {
      sb.append(this.noteId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("endpointName:");
    if (this.endpointName == null) {
      sb.append("null");
    } else {
      sb.append(this.endpointName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hostname:");
    if (this.hostname == null) {
      sb.append("null");
    } else {
      sb.append(this.hostname);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("serverPort:");
    sb.append(this.serverPort);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RestApiInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RestApiInfoStandardScheme getScheme() {
      return new RestApiInfoStandardScheme();
    }
  }

  private static class RestApiInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<RestApiInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RestApiInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INTP_GROUP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.intpGroupId = iprot.readString();
              struct.setIntpGroupIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NOTE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.noteId = iprot.readString();
              struct.setNoteIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENDPOINT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.endpointName = iprot.readString();
              struct.setEndpointNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HOSTNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hostname = iprot.readString();
              struct.setHostnameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SERVER_PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.serverPort = iprot.readI32();
              struct.setServerPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RestApiInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.intpGroupId != null) {
        oprot.writeFieldBegin(INTP_GROUP_ID_FIELD_DESC);
        oprot.writeString(struct.intpGroupId);
        oprot.writeFieldEnd();
      }
      if (struct.noteId != null) {
        oprot.writeFieldBegin(NOTE_ID_FIELD_DESC);
        oprot.writeString(struct.noteId);
        oprot.writeFieldEnd();
      }
      if (struct.endpointName != null) {
        oprot.writeFieldBegin(ENDPOINT_NAME_FIELD_DESC);
        oprot.writeString(struct.endpointName);
        oprot.writeFieldEnd();
      }
      if (struct.hostname != null) {
        oprot.writeFieldBegin(HOSTNAME_FIELD_DESC);
        oprot.writeString(struct.hostname);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SERVER_PORT_FIELD_DESC);
      oprot.writeI32(struct.serverPort);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RestApiInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RestApiInfoTupleScheme getScheme() {
      return new RestApiInfoTupleScheme();
    }
  }

  private static class RestApiInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<RestApiInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RestApiInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIntpGroupId()) {
        optionals.set(0);
      }
      if (struct.isSetNoteId()) {
        optionals.set(1);
      }
      if (struct.isSetEndpointName()) {
        optionals.set(2);
      }
      if (struct.isSetHostname()) {
        optionals.set(3);
      }
      if (struct.isSetServerPort()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetIntpGroupId()) {
        oprot.writeString(struct.intpGroupId);
      }
      if (struct.isSetNoteId()) {
        oprot.writeString(struct.noteId);
      }
      if (struct.isSetEndpointName()) {
        oprot.writeString(struct.endpointName);
      }
      if (struct.isSetHostname()) {
        oprot.writeString(struct.hostname);
      }
      if (struct.isSetServerPort()) {
        oprot.writeI32(struct.serverPort);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RestApiInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.intpGroupId = iprot.readString();
        struct.setIntpGroupIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.noteId = iprot.readString();
        struct.setNoteIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.endpointName = iprot.readString();
        struct.setEndpointNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.hostname = iprot.readString();
        struct.setHostnameIsSet(true);
      }
      if (incoming.get(4)) {
        struct.serverPort = iprot.readI32();
        struct.setServerPortIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

