kind: Pod
apiVersion: v1
metadata:
  namespace: default
  name: zeppelin-server
  labels:
    app: zeppelin-server
spec:
  automountServiceAccountToken: true
  containers:
  - name: zeppelin-server
    image: apache/zeppelin:0.9.0-SNAPSHOT
    command: ["sh", "-c", "$(ZEPPELIN_HOME)/bin/zeppelin.sh"]
    env:
    - name: ZEPPELIN_HOME
      value: /zeppelin
    - name: ZEPPELIN_SERVER_RPC_PORTRANGE
      value: 12320:12320
    - name: POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE
      value: spark:2.4.0
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: zeppelin-server    # keep Service name the same to Pod name.
spec:
  ports:
    - name: http
      port: 8080
    - name: rpc            # port name is referenced in the code. So it shouldn't be changed.
      port: 12320
  selector:
    app: zeppelin-server
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zeppelin-server-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zeppelin-server-role-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: zeppelin-server-role
  apiGroup: rbac.authorization.k8s.io
