kind: Pod
apiVersion: v1
metadata:
  namespace: {{NAMESPACE}}
  name: {{POD_NAME}}
  labels:
    app: {{POD_NAME}}
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: {{CONTAINER_NAME}}
    image: {{CONTAINER_IMAGE}}
    command: ["sh", "-c", "$(ZEPPELIN_HOME)/bin/interpreter.sh -d $(ZEPPELIN_HOME)/interpreter/{{INTP_NAME}} -r {{INTP_PORT}} -c {{CALLBACK_HOST}} -p {{CALLBACK_PORT}} -i {{INTP_ID}} -l {{INTP_REPO}} -g {{INTP_SETTING}}"]
    env:
    - name: ZEPPELIN_HOME
      value: /zeppelin
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{NAMESPACE}}
  name: {{POD_NAME}}             # keep Service name the same to Pod name.
spec:
  ports:
    - name: intp
      port: 12321
  selector:
    app: {{POD_NAME}}
