#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: Zeppelin CI

on: [push, pull_request]

jobs:
  # Test License compliance using RAT tool
  license-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean -B -Prat org.apache.rat:apache-rat-plugin:check

  # Default build command, no tests
  all-modules-build-only:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean package -B -T 2C -DskipTests

  # Run e2e and selenium tests
  web-e2e-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Start X
      env:
        DISPLAY: :99.0
      run: |
        sudo nohup Xvfb &
        sleep 3
    - name: Build with Maven
      run: |
        mvn package -B -T 2C -DskipTests -pl $(./testing/interpreters_exclude.sh)
    - name: Run test
      env:
        CI: true
        DISPLAY: :99.0
      run: |
        mvn verify -B -Pweb-e2e -Pintegration -pl zeppelin-web,zeppelin-integration -amd -DfailIfNoTests=false


  # Build distribution package and test core modules using distribution package
  test-core-modules-distr:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn package -B -T 2C -Pbuild-distr -DskipTests -Phelium-dev -Pexamples -pl $(./testing/interpreters_exclude.sh)
    - name: Run test
      env:
        PYTHON: 3
        SPARKR: true
      run: |
        mvn verify -B -Pusing-packaged-distr -Pspark-2.2 -Pspark-scala-2.11 -Phelium-dev -Pexamples -pl $(./testing/interpreters_exclude.sh) -Dtests.to.exclude=**/JdbcIntegrationTest.java,**/SparkIntegrationTest.java,**/ZeppelinSparkClusterTest.java,**/org/apache/zeppelin/spark/*,**/HeliumApplicationFactoryTest.java -DfailIfNoTests=false
